### ISSUE TITLE
No css for bibliography?

### ISSUE THREAD

**Issue by postylem** [jez/tufte-pandoc-css#5]
I was compiling HTML from markdown using pandoc with the `--citeproc` option, and I noticed that the bibliography looked bad (basically because there's no hanging indent).

Here is an example with tufte-pandoc-css
![Screen Shot 2021-06-24 at 16 24 52](https://user-images.githubusercontent.com/5202957/123334393-07fb4480-d511-11eb-9758-2e823e12b7b1.png)

Compare to the following (with the default css), it's clear that the lack of hanging indent makes it pretty unreadable.  

![Screen Shot 2021-06-24 at 16 25 09](https://user-images.githubusercontent.com/5202957/123334474-2c572100-d511-11eb-90e7-3b64dbdb3b3e.png)

This seems to be caused by the fact that no classes such as `div.csl-entry` are defined in tufte-css, or in the additional css files in this repo.
I hacked together a quick fix by copying things from the default css. This is what I added:

```css
div.csl-bib-body {
  /* font-size: 1.4rem; */
  /* line-height: 2rem; */
  width: 55%;
}
div.csl-entry {
  clear: both;
  margin-top: .25em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
div.hanging-indent{
  margin-left: 1.5em;
  text-indent: -1.5em;
}

@media (max-width: 760px) {
  div.csl-bib-body {
    width: 100%;
  }
}
```
to get the following
![Screen Shot 2021-06-24 at 17 21 57](https://user-images.githubusercontent.com/5202957/123334533-40028780-d511-11eb-9671-b02eac339da0.png)

This is better. But, a more comprehensive fix would be needed to make this work with arbitrary CSLs, I think (I'm just using the default Chicago author-year CSL, ones that make numbered references (e.g. Springer, or IEEE) would need additional attention.) Am I missing something, and is this fix not needed? Is fixing this something within the scope of this project?  

(Also, This repo is great. Thanks for putting it up!)
